
import SearchBar from "@/components/bookstore/searchbar";
import Link from "next/link"; 
import { ReactNode } from "react";
import type { Metadata } from "next";
import { BookData } from "../../../../types";

// 메타 데이터 // 
export const metadata: Metadata = {
    title: "한입 북스",
    description: "Generated by create next app"
}; 

// 헤더 // 
function Header() {
    return(
        <header className='flex w-1/4 text-3xl font-bold justify-start items-center'>
            <Link href={'/project/bookstore'}>📚서점</Link>
        </header>
    );
};

// 푸터 //
async function Footer() {
    const response = await fetch(`${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`);
    if(!response.ok) return <div>제작 @Kim</div>
    const books : BookData[] = await response.json();
    const bookCount = books.length;
    
    return(
        <footer className="text-sm">
            <div>제작 @김태영</div>
            <div>{ bookCount }개의 도서가 등록되어 있습니다.</div>
        </footer>
    );
};

export default function Page({children, modal}: Readonly<{children: ReactNode; modal: ReactNode;}>) {
    return (
        <div className="container mx-auto flex flex-col items-center justify-center gap-5">
            <Header />
            <main className="flex w-1/4 border">
                { children }
            </main>
            <Footer />
            { modal }
        </div>
    );
};