
import type { Metadata } from "next";
import ChatPeopleList from "@/components/instagram/chat-people-list";
import ChatScreen from "@/components/instagram/chat-screen";
import { createServerSupabaseClient } from "@/utils/supabase/server";

export const metadata: Metadata = {
    title: "인스타그램 채팅",
    description: "Generated by create next app",
};

export default async function Page() {

    const supabase = await createServerSupabaseClient();
    const { data: {session} } = await supabase.auth.getSession();

    return(
        <div className="flex flex-row items-center justify-center gap-5 border w-full">
            <ChatPeopleList loggedInUser={ session?.user } />
            <ChatScreen />
        </div>
    );
};