
import type { Metadata } from "next";
import Header from "@/components/netflix/header";
import MovieCardList from "@/components/netflix/movie-card-list"; 

export const metadata: Metadata = {
    title: "넷플릭스",
    description: "Generated by create next app",
};

export default function Page() {
    return(
        <div className="container mx-auto">
            <Header />
            <main className="mt-20">
                <MovieCardList />
            </main>
        </div>
    );
};